exchange_rates = {
    'USD - United States': {
        'EUR - Eurozone': {'rate': 0.85},
        'JPY - Japan': {'rate': 110.00},
        'GBP - United Kingdom': {'rate': 0.75},
        'AUD - Australia': {'rate': 1.30},
        'CAD - Canada': {'rate': 1.25},
        'CHF - Switzerland': {'rate': 0.92},
        'CNY - China': {'rate': 6.45},
        'SEK - Sweden': {'rate': 8.85},
        'NZD - New Zealand': {'rate': 1.45},
        'MXN - Mexico': {'rate': 21.50},
        'INR - India': {'rate': 75.00},
        'BRL - Brazil': {'rate': 5.30},
        'RUB - Russia': {'rate': 74.50},
        'HKD - Hong Kong': {'rate': 7.80},
        'SGD - Singapore': {'rate': 1.40},
        'KRW - South Korea': {'rate': 1200.00},
        'ZAR - South Africa': {'rate': 14.20},
    },
    'EUR - Eurozone': {
        'USD - United States': {'rate': 1.18},
        'JPY - Japan': {'rate': 130.00},
        'GBP - United Kingdom': {'rate': 0.88},
        'AUD - Australia': {'rate': 1.55},
        'CAD - Canada': {'rate': 1.48},
        'CHF - Switzerland': {'rate': 1.09},
        'CNY - China': {'rate': 7.65},
        'SEK - Sweden': {'rate': 10.45},
        'NZD - New Zealand': {'rate': 1.72},
        'MXN - Mexico': {'rate': 25.50},
        'INR - India': {'rate': 88.50},
        'BRL - Brazil': {'rate': 6.25},
        'RUB - Russia': {'rate': 88.20},
        'HKD - Hong Kong': {'rate': 9.20},
        'SGD - Singapore': {'rate': 1.65},
        'KRW - South Korea': {'rate': 1400.00},
        'ZAR - South Africa': {'rate': 16.60},
    },
    'JPY - Japan': {
        'USD - United States': {'rate': 0.0091},
        'EUR - Eurozone': {'rate': 0.0077},
        'GBP - United Kingdom': {'rate': 0.0072},
        'AUD - Australia': {'rate': 0.012},
        'CAD - Canada': {'rate': 0.011},
        'CHF - Switzerland': {'rate': 0.0083},
        'CNY - China': {'rate': 0.057},
        'SEK - Sweden': {'rate': 0.078},
        'NZD - New Zealand': {'rate': 0.013},
        'MXN - Mexico': {'rate': 1.92},
        'INR - India': {'rate': 0.67},
        'BRL - Brazil': {'rate': 0.12},
        'RUB - Russia': {'rate': 1.70},
        'HKD - Hong Kong': {'rate': 0.18},
        'SGD - Singapore': {'rate': 0.032},
        'KRW - South Korea': {'rate': 27.50},
        'ZAR - South Africa': {'rate': 0.33},
    },
    'GBP - United Kingdom': {
        'USD - United States': {'rate': 1.34},
        'EUR - Eurozone': {'rate': 1.14},
        'JPY - Japan': {'rate': 139.00},
        'AUD - Australia': {'rate': 1.75},
        'CAD - Canada': {'rate': 1.67},
        'CHF - Switzerland': {'rate': 1.23},
        'CNY - China': {'rate': 8.60},
        'SEK - Sweden': {'rate': 11.75},
        'NZD - New Zealand': {'rate': 1.93},
        'MXN - Mexico': {'rate': 28.60},
        'INR - India': {'rate': 99.50},
        'BRL - Brazil': {'rate': 7.05},
        'RUB - Russia': {'rate': 99.00},
        'HKD - Hong Kong': {'rate': 10.30},
        'SGD - Singapore': {'rate': 1.85},
        'KRW - South Korea': {'rate': 1570.00},
        'ZAR - South Africa': {'rate': 18.70},
    },
    'AUD - Australia': {
        'USD - United States': {'rate': 0.77},
        'EUR - Eurozone': {'rate': 0.64},
        'JPY - Japan': {'rate': 81.00},
        'GBP - United Kingdom': {'rate': 0.57},
        'CAD - Canada': {'rate': 0.95},
        'CHF - Switzerland': {'rate': 0.70},
        'CNY - China': {'rate': 4.95},
        'SEK - Sweden': {'rate': 6.75},
        'NZD - New Zealand': {'rate': 1.10},
        'MXN - Mexico': {'rate': 16.30},
        'INR - India': {'rate': 57.00},
        'BRL - Brazil': {'rate': 4.05},
        'RUB - Russia': {'rate': 56.80},
        'HKD - Hong Kong': {'rate': 5.90},
        'SGD - Singapore': {'rate': 1.06},
        'KRW - South Korea': {'rate': 910.00},
        'ZAR - South Africa': {'rate': 10.80},
    },
    'CAD - Canada': {
        'USD - United States': {'rate': 0.80},
        'EUR - Eurozone': {'rate': 0.68},
        'JPY - Japan': {'rate': 89.00},
        'GBP - United Kingdom': {'rate': 0.60},
        'AUD - Australia': {'rate': 1.05},
        'CHF - Switzerland': {'rate': 0.74},
        'CNY - China': {'rate': 5.25},
        'SEK - Sweden': {'rate': 7.15},
        'NZD - New Zealand': {'rate': 1.17},
        'MXN - Mexico': {'rate': 17.40},
        'INR - India': {'rate': 60.50},
        'BRL - Brazil': {'rate': 4.30},
        'RUB - Russia': {'rate': 60.20},
        'HKD - Hong Kong': {'rate': 6.30},
        'SGD - Singapore': {'rate': 1.13},
        'KRW - South Korea': {'rate': 970.00},
        'ZAR - South Africa': {'rate': 11.50},
    },
    'CHF - Switzerland': {
        'USD - United States': {'rate': 1.09},
        'EUR - Eurozone': {'rate': 0.92},
        'JPY - Japan': {'rate': 120.00},
        'GBP - United Kingdom': {'rate': 0.81},
        'AUD - Australia': {'rate': 1.43},
        'CAD - Canada': {'rate': 1.35},
        'CNY - China': {'rate': 7.05},
        'SEK - Sweden': {'rate': 9.60},
        'NZD - New Zealand': {'rate': 1.57},
        'MXN - Mexico': {'rate': 23.30},
        'INR - India': {'rate': 81.30},
        'BRL - Brazil': {'rate': 5.75},
        'RUB - Russia': {'rate': 80.70},
        'HKD - Hong Kong': {'rate': 8.40},
        'SGD - Singapore': {'rate': 1.51},
        'KRW - South Korea': {'rate': 1290.00},
        'ZAR - South Africa': {'rate': 15.30},
    },
    'CNY - China': {
        'USD - United States': {'rate': 0.15},
        'EUR - Eurozone': {'rate': 0.13},
        'JPY - Japan': {'rate': 17.50},
        'GBP - United Kingdom': {'rate': 0.12},
        'AUD - Australia': {'rate': 0.20},
        'CAD - Canada': {'rate': 0.19},
        'CHF - Switzerland': {'rate': 0.14},
        'SEK - Sweden': {'rate': 1.37},
        'NZD - New Zealand': {'rate': 0.22},
        'MXN - Mexico': {'rate': 3.30},
        'INR - India': {'rate': 11.50},
        'BRL - Brazil': {'rate': 0.82},
        'RUB - Russia': {'rate': 11.50},
        'HKD - Hong Kong': {'rate': 1.20},
        'SGD - Singapore': {'rate': 0.22},
        'KRW - South Korea': {'rate': 190.00},
        'ZAR - South Africa': {'rate': 2.25},
    },
    'SEK - Sweden': {
        'USD - United States': {'rate': 0.11},
        'EUR - Eurozone': {'rate': 0.095},
        'JPY - Japan': {'rate': 12.80},
        'GBP - United Kingdom': {'rate': 0.085},
        'AUD - Australia': {'rate': 0.15},
        'CAD - Canada': {'rate': 0.14},
        'CHF - Switzerland': {'rate': 0.10},
        'CNY - China': {'rate': 0.73},
        'NZD - New Zealand': {'rate': 0.17},
        'MXN - Mexico': {'rate': 2.60},
        'INR - India': {'rate': 9.10},
        'BRL - Brazil': {'rate': 0.64},
        'RUB - Russia': {'rate': 9.00},
        'HKD - Hong Kong': {'rate': 0.94},
        'SGD - Singapore': {'rate': 0.17},
        'KRW - South Korea': {'rate': 145.00},
        'ZAR - South Africa': {'rate': 1.72},
    },
    'NZD - New Zealand': {
        'USD - United States': {'rate': 0.69},
        'EUR - Eurozone': {'rate': 0.58},
        'JPY - Japan': {'rate': 74.00},
        'GBP - United Kingdom': {'rate': 0.52},
        'AUD - Australia': {'rate': 0.91},
        'CAD - Canada': {'rate': 0.87},
        'CHF - Switzerland': {'rate': 0.64},
        'CNY - China': {'rate': 4.45},
        'SEK - Sweden': {'rate': 5.90},
        'MXN - Mexico': {'rate': 13.80},
        'INR - India': {'rate': 48.00},
        'BRL - Brazil': {'rate': 3.40},
        'RUB - Russia': {'rate': 47.80},
        'HKD - Hong Kong': {'rate': 4.95},
        'SGD - Singapore': {'rate': 0.89},
        'KRW - South Korea': {'rate': 760.00},
        'ZAR - South Africa': {'rate': 9.00},
    },
    'MXN - Mexico': {
        'USD - United States': {'rate': 0.047},
        'EUR - Eurozone': {'rate': 0.040},
        'JPY - Japan': {'rate': 0.52},
        'GBP - United Kingdom': {'rate': 0.035},
        'AUD - Australia': {'rate': 0.061},
        'CAD - Canada': {'rate': 0.058},
        'CHF - Switzerland': {'rate': 0.043},
        'CNY - China': {'rate': 0.30},
        'SEK - Sweden': {'rate': 0.41},
        'NZD - New Zealand': {'rate': 0.073},
        'INR - India': {'rate': 3.30},
        'BRL - Brazil': {'rate': 0.23},
        'RUB - Russia': {'rate': 3.25},
        'HKD - Hong Kong': {'rate': 0.34},
        'SGD - Singapore': {'rate': 0.061},
        'KRW - South Korea': {'rate': 525.00},
        'ZAR - South Africa': {'rate': 6.25},
    },
    'INR - India': {
        'USD - United States': {'rate': 0.013},
        'EUR - Eurozone': {'rate': 0.011},
        'JPY - Japan': {'rate': 1.50},
        'GBP - United Kingdom': {'rate': 0.010},
        'AUD - Australia': {'rate': 0.018},
        'CAD - Canada': {'rate': 0.017},
        'CHF - Switzerland': {'rate': 0.012},
        'CNY - China': {'rate': 0.088},
        'SEK - Sweden': {'rate': 0.12},
        'NZD - New Zealand': {'rate': 0.019},
        'MXN - Mexico': {'rate': 0.29},
        'BRL - Brazil': {'rate': 0.071},
        'RUB - Russia': {'rate': 1.00},
        'HKD - Hong Kong': {'rate': 0.10},
        'SGD - Singapore': {'rate': 0.018},
        'KRW - South Korea': {'rate': 15.50},
        'ZAR - South Africa': {'rate': 0.18},
    },
    'BRL - Brazil': {
        'USD - United States': {'rate': 0.19},
        'EUR - Eurozone': {'rate': 0.16},
        'JPY - Japan': {'rate': 21.00},
        'GBP - United Kingdom': {'rate': 0.14},
        'AUD - Australia': {'rate': 0.25},
        'CAD - Canada': {'rate': 0.24},
        'CHF - Switzerland': {'rate': 0.18},
        'CNY - China': {'rate': 1.23},
        'SEK - Sweden': {'rate': 1.68},
        'NZD - New Zealand': {'rate': 0.28},
        'MXN - Mexico': {'rate': 4.00},
        'INR - India': {'rate': 14.00},
        'RUB - Russia': {'rate': 14.00},
        'HKD - Hong Kong': {'rate': 1.45},
        'SGD - Singapore': {'rate': 0.26},
        'KRW - South Korea': {'rate': 225.00},
        'ZAR - South Africa': {'rate': 2.67},
    },
    'RUB - Russia': {
        'USD - United States': {'rate': 0.013},
        'EUR - Eurozone': {'rate': 0.011},
        'JPY - Japan': {'rate': 0.59},
        'GBP - United Kingdom': {'rate': 0.010},
        'AUD - Australia': {'rate': 0.018},
        'CAD - Canada': {'rate': 0.017},
        'CHF - Switzerland': {'rate': 0.012},
        'CNY - China': {'rate': 0.088},
        'SEK - Sweden': {'rate': 0.12},
        'NZD - New Zealand': {'rate': 0.019},
        'MXN - Mexico': {'rate': 0.29},
        'INR - India': {'rate': 0.71},
        'BRL - Brazil': {'rate': 0.071},
        'HKD - Hong Kong': {'rate': 0.10},
        'SGD - Singapore': {'rate': 0.018},
        'KRW - South Korea': {'rate': 15.50},
        'ZAR - South Africa': {'rate': 0.18},
    },
    'HKD - Hong Kong': {
        'USD - United States': {'rate': 0.13},
        'EUR - Eurozone': {'rate': 0.11},
        'JPY - Japan': {'rate': 5.61},
        'GBP - United Kingdom': {'rate': 0.097},
        'AUD - Australia': {'rate': 0.17},
        'CAD - Canada': {'rate': 0.16},
        'CHF - Switzerland': {'rate': 0.12},
        'CNY - China': {'rate': 0.85},
        'SEK - Sweden': {'rate': 1.16},
        'NZD - New Zealand': {'rate': 0.19},
        'MXN - Mexico': {'rate': 2.80},
        'INR - India': {'rate': 9.50},
        'BRL - Brazil': {'rate': 0.69},
        'RUB - Russia': {'rate': 9.10},
        'SGD - Singapore': {'rate': 0.18},
        'KRW - South Korea': {'rate': 120.00},
        'ZAR - South Africa': {'rate': 1.43},
    },
    'SGD - Singapore': {
        'USD - United States': {'rate': 0.71},
        'EUR - Eurozone': {'rate': 0.60},
        'JPY - Japan': {'rate': 77.00},
        'GBP - United Kingdom': {'rate': 0.55},
        'AUD - Australia': {'rate': 0.94},
        'CAD - Canada': {'rate': 0.90},
        'CHF - Switzerland': {'rate': 0.66},
        'CNY - China': {'rate': 4.65},
        'SEK - Sweden': {'rate': 6.34},
        'NZD - New Zealand': {'rate': 1.04},
        'MXN - Mexico': {'rate': 15.50},
        'INR - India': {'rate': 54.00},
        'BRL - Brazil': {'rate': 3.82},
        'RUB - Russia': {'rate': 53.80},
        'HKD - Hong Kong': {'rate': 5.42},
        'KRW - South Korea': {'rate': 860.00},
        'ZAR - South Africa': {'rate': 10.20},
    },
    'KRW - South Korea': {
        'USD - United States': {'rate': 0.00083},
        'EUR - Eurozone': {'rate': 0.00071},
        'JPY - Japan': {'rate': 0.036},
        'GBP - United Kingdom': {'rate': 0.00064},
        'AUD - Australia': {'rate': 0.0011},
        'CAD - Canada': {'rate': 0.0010},
        'CHF - Switzerland': {'rate': 0.00077},
        'CNY - China': {'rate': 0.0053},
        'SEK - Sweden': {'rate': 0.0069},
        'NZD - New Zealand': {'rate': 0.0013},
        'MXN - Mexico': {'rate': 0.0019},
        'INR - India': {'rate': 0.065},
        'BRL - Brazil': {'rate': 0.0044},
        'RUB - Russia': {'rate': 0.065},
        'HKD - Hong Kong': {'rate': 0.0083},
        'SGD - Singapore': {'rate': 0.0012},
        'ZAR - South Africa': {'rate': 0.012},
    },
    'ZAR - South Africa': {
        'USD - United States': {'rate': 0.070},
        'EUR - Eurozone': {'rate': 0.060},
        'JPY - Japan': {'rate': 7.50},
        'GBP - United Kingdom': {'rate': 0.054},
        'AUD - Australia': {'rate': 0.093},
        'CAD - Canada': {'rate': 0.089},
        'CHF - Switzerland': {'rate': 0.066},
        'CNY - China': {'rate': 0.44},
        'SEK - Sweden': {'rate': 0.58},
        'NZD - New Zealand': {'rate': 0.11},
        'MXN - Mexico': {'rate': 1.60},
        'INR - India': {'rate': 5.60},
        'BRL - Brazil': {'rate': 0.38},
        'RUB - Russia': {'rate': 5.30},
        'HKD - Hong Kong': {'rate': 0.70},
        'SGD - Singapore': {'rate': 0.098},
        'KRW - South Korea': {'rate': 81.00},
    }
}

available_currencies = [
    'USD - United States',
    'EUR - Eurozone',
    'JPY - Japan',
    'GBP - United Kingdom',
    'AUD - Australia',
    'CAD - Canada',
    'CHF - Switzerland',
    'CNY - China',
    'SEK - Sweden',
    'NZD - New Zealand',
    'MXN - Mexico',
    'INR - India',
    'BRL - Brazil',
    'RUB - Russia',
    'HKD - Hong Kong',
    'SGD - Singapore',
    'KRW - South Korea',
    'ZAR - South Africa'
]